# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='الرقم الوظيفي')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('role', models.CharField(choices=[('admin', 'مشرف أعلى'), ('manager', 'مدير'), ('reviewer', 'مراجع'), ('intake', 'جامع بيانات')], max_length=20, verbose_name='الدور')),
                ('receive_email_notifications', models.BooleanField(default=True, verbose_name='إشعارات بريدية')),
                ('receive_sms_notifications', models.BooleanField(default=False, verbose_name='إشعارات SMS')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='اللغة')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط')),
                ('requests_handled', models.IntegerField(default=0, verbose_name='الطلبات المعالجة')),
                ('customers_managed', models.IntegerField(default=0, verbose_name='العملاء المتابعين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
