# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(verbose_name='حجم الملف (بايت)')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('category', models.CharField(choices=[('identity', 'صورة الهوية'), ('authorization', 'التفويض'), ('contract', 'عقد'), ('receipt', 'إيصال'), ('other', 'أخرى')], max_length=100, verbose_name='التصنيف')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_approved', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests.request', verbose_name='الطلب')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النسخة')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(verbose_name='حجم الملف (بايت)')),
                ('backup_type', models.CharField(choices=[('automatic', 'تلقائي'), ('manual', 'يدوي'), ('scheduled', 'مجدول')], max_length=20, verbose_name='النوع')),
                ('status', models.CharField(choices=[('in_progress', 'جارٍ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('verified', 'تم التحقق')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='مشفر')),
                ('encryption_method', models.CharField(default='AES-256', max_length=50, verbose_name='طريقة التشفير')),
                ('storage_location', models.CharField(choices=[('aws_s3', 'AWS S3'), ('google_drive', 'Google Drive'), ('local', 'محلي')], max_length=100, verbose_name='موقع التخزين')),
                ('file_hash', models.CharField(blank=True, max_length=128, verbose_name='Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_utils__status_1e8bfc_idx'), models.Index(fields=['created_at'], name='core_utils__created_4e7964_idx')],
            },
        ),
    ]
