# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('setting_type', models.CharField(choices=[('string', 'نص'), ('number', 'رقم'), ('boolean', 'صح/خطأ'), ('json', 'JSON')], default='string', max_length=20, verbose_name='النوع')),
                ('category', models.CharField(choices=[('general', 'عام'), ('payment', 'الدفع'), ('notifications', 'الإشعارات'), ('security', 'الأمان'), ('backup', 'النسخ الاحتياطي'), ('email', 'البريد الإلكتروني'), ('sms', 'الرسائل')], max_length=100, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل للتعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحديث بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد نظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['category', 'key'],
            },
        ),
    ]
