# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('currency', models.CharField(default='AED', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('processing', 'قيد المعالجة'), ('paid', 'مدفوع'), ('failed', 'فشل'), ('refunded', 'مسترد'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('payment_method', models.CharField(choices=[('paytabs', 'PayTabs'), ('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي')], default='paytabs', max_length=50, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم المعاملة')),
                ('payment_url', models.URLField(blank=True, verbose_name='رابط الدفع')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='استجابة البوابة')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الرابط')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الاسترداد')),
                ('refund_reason', models.TextField(blank=True, verbose_name='سبب الاسترداد')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاسترداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL, verbose_name='تم الاسترداد بواسطة')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='requests.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
