# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('name_english', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('content_arabic', models.TextField(verbose_name='المحتوى بالعربية')),
                ('content_english', models.TextField(blank=True, verbose_name='المحتوى بالإنجليزية')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='الإصدار')),
                ('template_type', models.CharField(choices=[('authorization', 'تفويض ربط حساب'), ('service_agreement', 'اتفاقية الخدمة'), ('financial_contract', 'عقد الخدمات المالية'), ('customer_declaration', 'إقرار العميل'), ('privacy_policy', 'سياسة الخصوصية'), ('disclaimer', 'إخلاء المسؤولية')], max_length=100, verbose_name='نوع القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('requires_admin_approval', models.BooleanField(default=True, verbose_name='يحتاج موافقة المشرف')),
                ('file', models.FileField(blank=True, upload_to='templates/', verbose_name='ملف القالب')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'القوالب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='الرقم المرجعي')),
                ('request_type', models.CharField(choices=[('paytabs_link', 'ربط حساب PayTabs'), ('payment_gateway', 'بوابة دفع'), ('merchant_account', 'حساب تاجر'), ('other', 'أخرى')], max_length=100, verbose_name='نوع الطلب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('new', 'جديد'), ('in_review', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('pending_payment', 'بانتظار الدفع'), ('paid', 'مدفوع'), ('processing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('on_hold', 'معلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('needs_approval', models.BooleanField(default=True, verbose_name='يحتاج موافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('checklist_completed', models.BooleanField(default=False, verbose_name='Checklist مكتمل')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='الهوية موثقة')),
                ('template_selected', models.BooleanField(default=False, verbose_name='القالب محدد')),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='الدفع مؤكد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة من')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='clients.customer', verbose_name='العميل')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_deleted', to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفض من')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='requests.template', verbose_name='القالب القانوني')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
                'permissions': [('approve_request', 'يمكنه الموافقة على الطلبات'), ('reject_request', 'يمكنه رفض الطلبات'), ('can_delete_request', 'يمكنه حذف الطلبات'), ('view_all_requests', 'يمكنه رؤية جميع الطلبات')],
                'indexes': [models.Index(fields=['reference_number'], name='requests_re_referen_c32679_idx'), models.Index(fields=['status'], name='requests_re_status_039311_idx'), models.Index(fields=['created_at'], name='requests_re_created_1c052d_idx')],
            },
        ),
    ]
