# Generated by Django 5.2.7 on 2025-10-13 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type_legacy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الطلب (قديم)'),
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_english', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('category', models.CharField(choices=[('paytabs', 'خدمات PayTabs'), ('payment_gateway', 'بوابات الدفع'), ('merchant', 'حسابات تجارية'), ('bank', 'تكاملات بنكية'), ('additional', 'خدمات إضافية'), ('other', 'أخرى')], max_length=50, verbose_name='الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('default_price', models.DecimalField(decimal_places=2, default=420.0, max_digits=10, verbose_name='السعر الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوع طلب',
                'verbose_name_plural': 'أنواع الطلبات',
                'ordering': ['category', 'display_order', 'name_arabic'],
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='requests.requesttype', verbose_name='نوع الطلب'),
        ),
    ]
