# Generated by Django 5.2.7 on 2025-10-13 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_request_type_legacy_requesttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='الرمز')),
                ('icon', models.CharField(default='fa-list', help_text='مثال: fa-credit-card', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(choices=[('primary', 'أزرق'), ('success', 'أخضر'), ('warning', 'أصفر'), ('info', 'سماوي'), ('danger', 'أحمر'), ('secondary', 'رمادي')], default='primary', max_length=20, verbose_name='اللون')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['display_order', 'name_arabic'],
            },
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'ordering': ['display_order', 'name_arabic'], 'verbose_name': 'نوع طلب', 'verbose_name_plural': 'أنواع الطلبات'},
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_types', to='requests.requestcategory', verbose_name='الفئة'),
        ),
    ]
