# Generated by Django 5.2.7 on 2025-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_requestcategory_alter_requesttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcategory',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='مثال: fa-file-alt (اختياري)', max_length=50, verbose_name='الأيقونة'),
        ),
    ]
