# Generated by Django 5.2.7 on 2025-10-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_requestcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_english',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
    ]
