# Generated by Django 5.2.7 on 2025-10-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_template_code_alter_template_name_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_english', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='الرمز')),
                ('icon', models.CharField(blank=True, default='fa-file-alt', help_text='مثال: fa-file-alt (اختياري)', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(choices=[('primary', 'أزرق'), ('success', 'أخضر'), ('warning', 'أصفر'), ('info', 'سماوي'), ('danger', 'أحمر'), ('secondary', 'رمادي'), ('dark', 'أسود'), ('light', 'فاتح')], default='primary', max_length=20, verbose_name='اللون')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'نوع قالب',
                'verbose_name_plural': 'أنواع القوالب',
                'ordering': ['display_order', 'name_arabic'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='template_type_legacy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع القالب (قديم)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='requests.templatetype', verbose_name='نوع القالب'),
        ),
    ]
