# Generated by Django 5.2.7 on 2025-10-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_templatetype_template_template_type_legacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='requires_admin_approval',
        ),
    ]
