# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'عرض'), ('approve', 'موافقة'), ('reject', 'رفض'), ('payment', 'دفع'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('export', 'تصدير'), ('print', 'طباعة'), ('restore', 'استعادة')], max_length=50, verbose_name='العملية')),
                ('model_name', models.CharField(max_length=100, verbose_name='نوع الكيان')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='معرف الكيان')),
                ('object_repr', models.CharField(max_length=200, verbose_name='تمثيل الكيان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='القيم الجديدة')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الأهمية')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
