# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الرباعي')),
                ('full_name_english', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('emirates_id', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون بصيغة: 784-XXXX-XXXXXXX-X', regex='^784-\\d{4}-\\d{7}-\\d{1}$')], verbose_name='رقم الهوية')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('nationality', models.CharField(default='الإمارات', max_length=100, verbose_name='الجنسية')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='المهنة')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('same_name_diff_id', 'نفس الاسم - هوية مختلفة'), ('same_id_diff_name', 'نفس الهوية - اسم مختلف'), ('similar_name', 'أسماء متشابهة')], max_length=50, verbose_name='نوع التعارض')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('reviewing', 'قيد المراجعة'), ('resolved', 'تم الحل'), ('ignored', 'تم التجاهل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('resolution', models.TextField(blank=True, verbose_name='الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف')),
                ('customer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='clients.customer', verbose_name='العميل الأول')),
                ('customer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='clients.customer', verbose_name='العميل الثاني')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
            ],
            options={
                'verbose_name': 'تعارض هوية',
                'verbose_name_plural': 'تعارضات الهوية',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['emirates_id'], name='clients_cus_emirate_1836e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['full_name'], name='clients_cus_full_na_242575_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='clients_cus_phone_60eb1d_idx'),
        ),
    ]
