# Generated by Django 5.2.7 on 2025-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_ids/', verbose_name='صورة الهوية الإماراتية'),
        ),
    ]
