# Generated by Django 5.2.7 on 2025-10-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_customer_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/id_images/', verbose_name='صورة الهوية'),
        ),
    ]
