# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('report_type', models.CharField(choices=[('requests_summary', 'ملخص الطلبات'), ('customers_summary', 'ملخص العملاء'), ('payments_summary', 'ملخص المدفوعات'), ('audit_trail', 'سجل التدقيق'), ('performance', 'الأداء'), ('custom', 'مخصص')], max_length=100, verbose_name='نوع التقرير')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='إلى تاريخ')),
                ('filters', models.JSONField(default=dict, verbose_name='الفلاتر')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='النتائج')),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='ملف التقرير')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20, verbose_name='صيغة الملف')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('generating', 'جارٍ التوليد'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحميل')),
                ('download_count', models.IntegerField(default=0, verbose_name='عدد التحميلات')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التوليد بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-generated_at'],
            },
        ),
    ]
