# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التنبيه')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('alert_type', models.CharField(choices=[('overdue_requests', 'طلبات متأخرة'), ('birthday', 'أعياد ميلاد'), ('identity_conflict', 'تعارضات الهوية'), ('backup', 'النسخ الاحتياطي'), ('pending_payment', 'مدفوعات معلقة'), ('missing_docs', 'مستندات ناقصة'), ('approval_needed', 'تحتاج موافقة'), ('custom', 'مخصص')], max_length=50, verbose_name='النوع')),
                ('condition', models.TextField(verbose_name='الشرط')),
                ('frequency', models.CharField(choices=[('realtime', 'فوري'), ('hourly', 'كل ساعة'), ('daily', 'يومياً'), ('weekly', 'أسبوعياً'), ('monthly', 'شهرياً')], default='daily', max_length=20, verbose_name='التكرار')),
                ('action', models.CharField(choices=[('notify_user', 'إشعار المستخدم'), ('send_email', 'إرسال بريد'), ('send_sms', 'إرسال رسالة'), ('all', 'جميع ما سبق')], default='notify_user', max_length=100, verbose_name='الإجراء')),
                ('target_roles', models.JSONField(default=list, verbose_name='الأدوار المستهدفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنفيذ')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التنفيذ القادم')),
                ('execution_count', models.IntegerField(default=0, verbose_name='عدد مرات التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_created', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المستهدفون')),
            ],
            options={
                'verbose_name': 'تنبيه ذكي',
                'verbose_name_plural': 'التنبيهات الذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_new', 'طلب جديد'), ('request_approved', 'طلب موافق عليه'), ('request_rejected', 'طلب مرفوض'), ('payment_pending', 'دفع معلق'), ('payment_completed', 'دفع مكتمل'), ('birthday', 'عيد ميلاد'), ('identity_conflict', 'تعارض هوية'), ('overdue', 'طلب متأخر'), ('system', 'نظام')], max_length=50, verbose_name='النوع')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
