# Generated by Django 5.2.7 on 2025-10-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('video', 'فيديو'), ('audio', 'صوت')], default='text', max_length=20, verbose_name='النوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('file', models.FileField(blank=True, upload_to='chat/%Y/%m/', verbose_name='ملف مرفق')),
                ('direction', models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=10, verbose_name='الاتجاه')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('delivery_status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'مرسل'), ('delivered', 'تم التوصيل'), ('read', 'مقروء'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة التوصيل')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='WhatsApp Message ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.customer', verbose_name='العميل')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='requests.request', verbose_name='الطلب المرتبط')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['customer', 'sent_at'], name='chat_chatme_custome_8a401f_idx'), models.Index(fields=['whatsapp_message_id'], name='chat_chatme_whatsap_c4b25e_idx')],
            },
        ),
    ]
